### ISSUE TITLE
persist previews in moodle db

### ISSUE THREAD

**Issue by brendanheywood** [Catalyst-QUT-2023/moodle#13]
- [x] decide if we will store based on url alone, or the canonical url / og:url
- [x] create db schema for storing url data
- [x] when loading a url pass in an optional param to just grab from the store, or block and wait for the curl to happen
- [x] persist all the data, along with timestamps etc - use a persistent object for this https://docs.moodle.org/dev/Persistent
- [ ] when loading a preview store a 'lastpreviewed' timestamp, but only update this once an hour or day this only need to be a rough heuristic for when it was last used

**Comment by Palagen** [comment]
https://moodledev.io/docs/apis/subsystems/external/writing-a-service
